USE [master]
GO

/****** Object:  Database [ControleEstoque]    Script Date: 27/11/2015 21:57:21 ******/
CREATE DATABASE [ControleEstoque]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ControleEstoque', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\ControleEstoque.mdf' , SIZE = 90112KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ControleEstoque_log', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\ControleEstoque_log.ldf' , SIZE = 388544KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ControleEstoque] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ControleEstoque].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ControleEstoque] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ControleEstoque] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ControleEstoque] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ControleEstoque] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ControleEstoque] SET ARITHABORT OFF 
GO

ALTER DATABASE [ControleEstoque] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ControleEstoque] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ControleEstoque] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ControleEstoque] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ControleEstoque] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ControleEstoque] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ControleEstoque] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ControleEstoque] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ControleEstoque] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ControleEstoque] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ControleEstoque] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ControleEstoque] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ControleEstoque] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ControleEstoque] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ControleEstoque] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ControleEstoque] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ControleEstoque] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ControleEstoque] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ControleEstoque] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ControleEstoque] SET  MULTI_USER 
GO

ALTER DATABASE [ControleEstoque] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ControleEstoque] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ControleEstoque] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ControleEstoque] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ControleEstoque] SET  READ_WRITE 
GO


